#!/usr/bin/env python
"""
Generate EVERY table and figure in the paper from the result CSVs.

    python3 make_paper_assets.py [--out ../../../paper-satml2027/generated]

WHY THIS EXISTS. Numbers that are retyped into LaTeX drift from the data, and
nothing catches it. An earlier draft of Section 3 claimed "18/18 configurations"
where the CSV supports 15 of 18; that survived only because a human typed it.
Every figure and table the paper prints is emitted here, from the CSV, with the
source file and filter recorded in a comment at the top of each generated file.
Re-run this and rebuild rather than editing anything in generated/.

Outputs (all LaTeX, all self-contained, \\input-ed by the section files):
  tab_surface.tex    parameter surface either side of the vacuity boundary
  tab_omega.tex      attacker keyword survival by model x omega
  tab_vanilla.tex    benign drop vs vanilla RAG, and undefended ASR
  tab_benefit.tex    defense benefit vs the model's own undefended vulnerability
  tab_fix.tex        the floor2 / k mitigation
  fig_ladder.tex     survival vs omega, one line per model  (pgfplots)
  fig_benefit.tex    undefended ASR vs defense benefit, with the inversion
  (fig_tradeoff.tex is deliberately NOT generated; see its section below)
"""
import argparse
import collections
import csv
import math
import os

ap = argparse.ArgumentParser()
# The default writes straight into the paper's tree, which is one level above a
# released copy of this repository and therefore absent for anyone who only has
# the code. Rather than creating '../../../paper-satml2027/generated' out of
# nothing -- which would silently scatter .tex files outside the checkout --
# fall back to a local directory and say so. Pass --out to override either way.
ap.add_argument('--out', default=None,
                help='where to write the .tex assets '
                     '(default: the paper tree if present, else ./generated)')
ap.add_argument('--results', default='results')
A = ap.parse_args()
_PAPER = '../../../paper-satml2027/generated'
if A.out is not None:
    OUT = A.out
elif os.path.isdir(os.path.dirname(_PAPER)):
    OUT = _PAPER
else:
    OUT = 'generated'
    print(f'note: the paper tree is not present, so assets go to ./{OUT}/ .')
    print( '      This is expected for a standalone copy of the code; the '
           'assets are identical either way.')
R = A.results
os.makedirs(OUT, exist_ok=True)

OMEGA = os.path.join(R, 'omega_realtimeqa_k10_all.csv')
VAN = os.path.join(R, 'vanilla_realtimeqa_k10.csv')
SWEEP = os.path.join(R, 'sweep.csv')
FIX = os.path.join(R, 'fix_realtimeqa_k10_all.csv')

# Display names and the order models appear in every table, so the paper is
# internally consistent. Ordered by family then capability.
NAMES = [
    ('mistral7b-bedrock', 'Mistral-7B'),
    ('llama8b-bedrock', 'Llama-3.1-8B'),
    ('llama70b-bedrock', 'Llama-3.3-70B'),
    ('nova-micro-bedrock', 'Nova Micro'),
    ('nova-lite-bedrock', 'Nova Lite'),
    ('nova-pro-bedrock', 'Nova Pro'),
]
DISP = dict(NAMES)
ORDER = [m for m, _ in NAMES]
OMEGAS = [1, 2, 3, 4, 5]


def rows(path):
    if not os.path.exists(path):
        print(f'  !! missing {path} -- skipping the assets that need it')
        return []
    with open(path) as fh:
        return list(csv.DictReader(fh))


def pct(xs):
    return 100.0 * sum(xs) / len(xs) if xs else float('nan')


def mcnemar_exact(b, c):
    n = b + c
    if n == 0:
        return 1.0
    return min(1.0, 2 * sum(math.comb(n, i) for i in range(min(b, c) + 1)) / 2 ** n)


def fmt_p(p):
    return 'p < 0.001' if p < 0.001 else f'p = {p:.3f}'


def write(name, body, source, note=''):
    head = (f'% GENERATED by make_paper_assets.py -- DO NOT EDIT BY HAND.\n'
            f'% source: {source}\n')
    if note:
        head += ''.join(f'% {l}\n' for l in note.strip().splitlines())
    p = os.path.join(OUT, name)
    with open(p, 'w') as fh:
        fh.write(head + body)
    print(f'  wrote {p}')


# =====================================================================
om = rows(OMEGA)
van = rows(VAN)

surv = collections.defaultdict(list)   # (model, omega) -> [0/1]
vac = collections.defaultdict(list)
clean = collections.defaultdict(list)
dasr = collections.defaultdict(list)
for r in om:
    m, w = r['model'], int(r['group_size'])
    if r['k_prime'] == '1':
        surv[(m, w)].append(int(r['attacker_kw_survived']))
        vac[(m, w)].append(1 if float(r['mu']) <= 1.0 else 0)
        a = str(r.get('defended_asr', '')).strip()
        if a != '':
            dasr[(m, w)].append(int(a))
    elif r['k_prime'] == '0':
        c = str(r.get('defended_correct', '')).strip()
        if c != '':
            clean[(m, w)].append(int(c))

vacc = collections.defaultdict(list)   # model -> [0/1] vanilla clean correct
vasr = collections.defaultdict(list)   # model -> [0/1] vanilla ASR
for r in van:
    if r['attack'] == 'none':
        vacc[r['model']].append(int(r['undefended_correct']))
    else:
        a = str(r.get('undefended_asr', '')).strip()
        if a != '':
            vasr[r['model']].append(int(a))

present = [m for m in ORDER if surv.get((m, 1))]

# ---------------------------------------------------------------- tab_omega
if present:
    b = ['\\begin{table}[t]', '  \\centering',
         '  \\caption{Attacker keyword survival with a single poisoned passage '
         '($k\'=1$). At $\\omega\\ge4$ the filter is vacuous on every query for '
         'every model (Theorem~\\ref{thm:unconditional}); what remains is the '
         'model\'s own resistance.}',
         '  \\label{tab:omega}', '  \\begin{tabular}{l' + 'r' * len(OMEGAS) + '}',
         '    \\toprule',
         '    model & ' + ' & '.join(f'$\\omega{{=}}{w}$' for w in OMEGAS) + ' \\\\',
         '    \\midrule']
    for m in present:
        cells = []
        for w in OMEGAS:
            v = pct(surv[(m, w)])
            s = f'{v:.0f}\\%'
            if w >= 4:
                s = f'\\textbf{{{s}}}'
            cells.append(s)
        b.append(f'    {DISP[m]} & ' + ' & '.join(cells) + ' \\\\')
    b += ['    \\bottomrule', '  \\end{tabular}', '\\end{table}']
    write('tab_omega.tex', '\n'.join(b) + '\n', OMEGA,
          'filter: k_prime=1, metric attacker_kw_survived, 100 queries per cell')

# ---------------------------------------------------------------- tab_vanilla
if present and vacc:
    b = ['\\begin{table*}[t]', '  \\centering',
         '  \\caption{Benign accuracy relative to vanilla RAG (percentage points; '
         'negative means the defense costs accuracy), and the undefended attack '
         'success rate. The final column is the control that establishes the '
         'attack works at all.}',
         '  \\label{tab:vanilla}',
         '  \\begin{tabular}{lr' + 'r' * len(OMEGAS) + 'r}', '    \\toprule',
         '    & vanilla & \\multicolumn{%d}{c}{benign drop vs.\\ vanilla} & undef. \\\\'
         % len(OMEGAS),
         '    model & acc. & ' + ' & '.join(f'$\\omega{{=}}{w}$' for w in OMEGAS)
         + ' & ASR \\\\', '    \\midrule']
    for m in present:
        if not vacc.get(m):
            continue
        va = pct(vacc[m])
        cells = [f'{pct(clean[(m, w)]) - va:+.0f}' if clean.get((m, w)) else '--'
                 for w in OMEGAS]
        asr = f'{pct(vasr[m]):.0f}\\%' if vasr.get(m) else '--'
        b.append(f'    {DISP[m]} & {va:.0f}\\% & ' + ' & '.join(cells)
                 + f' & {asr} \\\\')
    b += ['    \\bottomrule', '  \\end{tabular}', '\\end{table*}']
    write('tab_vanilla.tex', '\n'.join(b) + '\n', f'{VAN} joined to {OMEGA} on (model,q_idx)',
          'benign drop: k_prime=0 defended_correct minus vanilla attack=none\n'
          'undefended ASR: vanilla attack=KeywordInjection, undefended_asr')

# ---------------------------------------------------------------- tab_benefit
# Paired per query: undefended ASR (vanilla) against defended ASR at omega=1.
# The captions of tab_benefit and fig_benefit quote the test for any model whose
# point estimate goes the wrong way, so that the caption says what the body says
# ("no measurable benefit") instead of calling a non-significant rise "harm".
_van_q = {(r['model'], r['q_idx']): int(r['undefended_asr']) for r in van
          if r['attack'] != 'none' and str(r.get('undefended_asr', '')).strip() != ''}
_def_q = {(r['model'], r['q_idx']): int(r['defended_asr']) for r in om
          if r['k_prime'] == '1' and r['group_size'] == '1'
          and str(r.get('defended_asr', '')).strip() != ''}
_worse = []
for _m in present:
    if not (vasr.get(_m) and dasr.get((_m, 1))) or pct(dasr[(_m, 1)]) <= pct(vasr[_m]):
        continue
    _keys = [k for k in _van_q if k[0] == _m and k in _def_q]
    _b = sum(1 for k in _keys if _van_q[k] == 1 and _def_q[k] == 0)
    _c = sum(1 for k in _keys if _van_q[k] == 0 and _def_q[k] == 1)
    _worse.append((_m, pct(dasr[(_m, 1)]) - pct(vasr[_m]), _b, _c, mcnemar_exact(_b, _c)))
_worse_txt = ''.join(
    f' For {DISP[_m]} attack success rises by {_d:.0f} points, which is not '
    f'significant (McNemar exact ${fmt_p(_p)}$, $b{{=}}{_b}$, $c{{=}}{_c}$).'
    if _p >= 0.05 else
    f' For {DISP[_m]} attack success rises by {_d:.0f} points '
    f'(McNemar exact ${fmt_p(_p)}$, $b{{=}}{_b}$, $c{{=}}{_c}$).'
    for _m, _d, _b, _c, _p in _worse)

if present and vasr:
    b = ['\\begin{table}[t]', '  \\centering',
         '  \\caption{The change in attack success rate the defense makes at '
         '$\\omega{=}1$, with both sides measured in the same units. Negative '
         'values are reductions, and the reduction grows with the model\'s '
         'undefended vulnerability.' + _worse_txt + '}',
         '  \\label{tab:benefit}', '  \\setlength{\\tabcolsep}{4pt}',
         '  \\begin{tabular}{lrrr}', '    \\toprule',
         '    model & undefended & defended ($\\omega{=}1$) & change \\\\',
         '    \\midrule']
    ranked = sorted([m for m in present if vasr.get(m)],
                    key=lambda m: -pct(vasr[m]))
    for m in ranked:
        u = pct(vasr[m])
        d = pct(dasr[(m, 1)]) if dasr.get((m, 1)) else float('nan')
        row = f'    {DISP[m]} & {u:.0f}\\% & {d:.0f}\\% & {d - u:+.0f}\\,pt \\\\'
        if d - u > 0:
            row = row.replace(f'{d - u:+.0f}\\,pt', f'\\textbf{{{d - u:+.0f}\\,pt}}')
        b.append(row)
    b += ['    \\bottomrule', '  \\end{tabular}', '\\end{table}']
    write('tab_benefit.tex', '\n'.join(b) + '\n', f'{VAN} and {OMEGA}',
          'both columns are ASR so they are directly comparable')

# ---------------------------------------------------------------- tab_surface
sw = rows(SWEEP)
if sw:
    cells = collections.defaultdict(lambda: collections.defaultdict(list))
    for r in sw:
        if r['k_prime'] != '1':
            continue
        key = (float(r['alpha']), float(r['beta']), r['model'])
        cells[key][float(r['mu']) <= 1.0].append(int(r['attacker_kw_survived']))
    by_alpha = collections.defaultdict(lambda: ([], []))
    n_straddle = 0
    for (al, be, m), d in cells.items():
        v, n = d.get(True, []), d.get(False, [])
        if v and n:
            n_straddle += 1
        by_alpha[al][0].extend(v)
        by_alpha[al][1].extend(n)
    allv = [x for al in by_alpha for x in by_alpha[al][0]]
    alln = [x for al in by_alpha for x in by_alpha[al][1]]
    b = ['\\begin{table}[t]', '  \\centering',
         '  \\caption{Attacker keyword survival either side of the vacuity '
         'boundary, pooled over $\\beta$ and over three models ($k\'=1$). '
         'Configurations with $\\alpha{=}0.1$ are vacuous on every query and '
         'therefore provide no contrast; they are shown but excluded from the '
         'agreement count.}',
         '  \\label{tab:surface}', '  \\begin{tabular}{lrr}', '    \\toprule',
         '    & $\\mu \\le 1$ & $\\mu > 1$ \\\\', '    \\midrule']
    for al in sorted(by_alpha):
        v, n = by_alpha[al]
        lab = f'$\\alpha={al}$' + ('$^\\dagger$' if not n else '')
        fv = f'{pct(v):.0f}\\% ({len(v)})' if v else '--'
        fn = f'{pct(n):.0f}\\% ({len(n)})' if n else '--'
        b.append(f'    {lab} & {fv} & {fn} \\\\')
    b += ['    \\midrule',
          f'    pooled & \\textbf{{{pct(allv):.1f}\\%}} ({len(allv)}) & '
          f'\\textbf{{{pct(alln):.1f}\\%}} ({len(alln)}) \\\\',
          '    \\bottomrule', '  \\end{tabular}', '\\end{table}']
    write('tab_surface.tex', '\n'.join(b) + '\n', SWEEP,
          f'k_prime=1; {n_straddle} of {len(cells)} (alpha,beta,model) cells '
          f'straddle the boundary\n'
          'cell counts in parentheses are query-rows, not cells')

# ---------------------------------------------------------------- tab_fix
fx = rows(FIX)
if fx:
    d = collections.defaultdict(list)
    for r in fx:
        if r['k_prime'] != '1':
            continue
        d[(r['model'], int(r['group_size']), r['threshold_mode'])].append(
            int(r['attacker_kw_survived']))
    dc = collections.defaultdict(list)
    for r in fx:
        if r['k_prime'] != '0':
            continue
        c = str(r.get('defended_correct', '')).strip()
        if c != '':
            dc[(r['model'], int(r['group_size']), r['threshold_mode'])].append(int(c))
    ws = sorted({w for _, w, _ in d})
    modes = ['n', 'floor2', 'k']
    lbl = {'n': 'upstream $\\min(\\alpha n,\\beta)$',
           'floor2': '$\\max(2,\\min(\\alpha n,\\beta))$',
           'k': '$\\min(\\alpha k,\\beta)$'}
    ms = [m for m in ORDER if any((m, w, 'n') in d for w in ws)]
    b = ['\\begin{table*}[t]', '  \\centering',
         '  \\caption{The mitigation. Flooring $\\mu$ at two corroborating '
         'responses closes both routes. It leaves clean accuracy unchanged at '
         '$\\omega{=}1$ and costs some at $\\omega{=}4$; replacing the adaptive '
         'term with a constant costs considerably more.}',
         '  \\label{tab:fix}',
         '  \\begin{tabular}{ll' + 'rr' * len(ws) + '}', '    \\toprule',
         '    & & ' + ' & '.join('\\multicolumn{2}{c}{$\\omega{=}%d$}' % w for w in ws)
         + ' \\\\',
         '    model & threshold & ' + ' & '.join('surv. & clean' for _ in ws) + ' \\\\',
         '    \\midrule']
    for m in ms:
        for i, mo in enumerate(modes):
            cells = []
            for w in ws:
                s = d.get((m, w, mo)); c = dc.get((m, w, mo))
                cells.append(f'{pct(s):.0f}\\%' if s else '--')
                cells.append(f'{pct(c):.0f}\\%' if c else '--')
            name = DISP[m] if i == 0 else ''
            b.append(f'    {name} & {lbl[mo]} & ' + ' & '.join(cells) + ' \\\\')
        b.append('    \\addlinespace')
    b += ['    \\bottomrule', '  \\end{tabular}', '\\end{table*}']
    # Clean accuracy, floor against upstream, paired on (model, q_idx). Section
    # VIII quotes these, so the claim about what the floor costs in clean
    # accuracy comes from the data at each omega rather than from the pooled
    # table cells. At omega=4 the floor does cost accuracy; the prose must say so.
    _cq = {(r['model'], int(r['group_size']), r['threshold_mode'], r['q_idx']):
           int(r['defended_correct']) for r in fx
           if r['k_prime'] == '0' and str(r.get('defended_correct', '')).strip() != ''}
    _facts = []
    for w, word in ((1, 'one'), (4, 'four')):
        _keys = [(m, q) for (m, ww, mo, q) in _cq if ww == w and mo == 'n'
                 and (m, w, 'floor2', q) in _cq]
        _lost = sum(1 for m, q in _keys if _cq[(m, w, 'n', q)] and not _cq[(m, w, 'floor2', q)])
        _gain = sum(1 for m, q in _keys if _cq[(m, w, 'floor2', q)] and not _cq[(m, w, 'n', q)])
        _up = pct([_cq[(m, w, 'n', q)] for m, q in _keys])
        _fl = pct([_cq[(m, w, 'floor2', q)] for m, q in _keys])
        _facts += [f'\\newcommand{{\\fixcleanlost{word}}}{{{_lost}}}',
                   f'\\newcommand{{\\fixcleangain{word}}}{{{_gain}}}',
                   f'\\newcommand{{\\fixcleanp{word}}}{{{fmt_p(mcnemar_exact(_lost, _gain))}}}',
                   f'\\newcommand{{\\fixcleanup{word}}}{{{_up:.0f}}}',
                   f'\\newcommand{{\\fixcleanfl{word}}}{{{_fl:.0f}}}']
        print(f'  [fix] clean acc omega={w}: upstream {_up:.1f}% floor {_fl:.1f}% '
              f'lost {_lost} gained {_gain} {fmt_p(mcnemar_exact(_lost, _gain))}')
    write('tab_fix.tex', '\n'.join(_facts + b) + '\n', FIX,
          'surv.: k_prime=1 attacker_kw_survived; clean: k_prime=0 defended_correct\n'
          'fixclean*: clean accuracy upstream vs floor2, paired on (model,q_idx), '
          'exact McNemar')

# ---------------------------------------------------------------- fig_ladder
if present:
    MARKS = ['*', 'square*', 'triangle*', 'diamond*', 'pentagon*', 'o']
    b = ['\\begin{figure}[t]', '  \\centering', '  \\begin{tikzpicture}',
         '    \\begin{axis}[width=\\columnwidth, height=5.4cm,',
         '      xlabel={passage group size $\\omega$},',
         '      ylabel={attacker survival (\\%)},',
         '      xtick={1,2,3,4,5}, ymin=0, ymax=105,',
         '      legend style={font=\\scriptsize, at={(0.02,0.98)}, anchor=north west,'
         ' draw=none, fill opacity=0.8, text opacity=1},',
         '      legend cell align=left, grid=major, grid style={gray!20},',
         '      tick label style={font=\\footnotesize},'
         ' label style={font=\\footnotesize}]']
    # shade the vacuous region omega>=4
    b.append('      \\addplot[draw=none, fill=gray!12, forget plot] coordinates '
             '{(3.5,0) (5.5,0) (5.5,105) (3.5,105)} \\closedcycle;')
    b.append('      \\node[font=\\scriptsize, anchor=north east] at (axis cs:5.4,100) '
             '{$\\mu\\le1$};')
    for i, m in enumerate(present):
        pts = ' '.join(f'({w},{pct(surv[(m, w)]):.1f})' for w in OMEGAS)
        b.append(f'      \\addplot[mark={MARKS[i % len(MARKS)]}, mark size=1.6pt, '
                 f'thick] coordinates {{{pts}}};')
        b.append(f'      \\addlegendentry{{{DISP[m]}}}')
    b += ['    \\end{axis}', '  \\end{tikzpicture}',
          '  \\caption{Attacker keyword survival against passage group size. The '
          'shaded region is where $\\lceil k/\\omega\\rceil \\le 1/\\alpha$ holds and '
          'the filter is vacuous by Theorem~\\ref{thm:unconditional}. Five of six '
          'models collapse there; Llama-3.3-70B does not, for a reason the '
          'undefended control explains (Section~\\ref{sec:gate}).}',
          '  \\label{fig:ladder}', '\\end{figure}']
    write('fig_ladder.tex', '\n'.join(b) + '\n', OMEGA,
          'k_prime=1, attacker_kw_survived, by (model, group_size)')

# ---------------------------------------------------------------- fig_benefit
if present and vasr:
    b = ['\\begin{figure}[t]', '  \\centering', '  \\begin{tikzpicture}',
         '    \\begin{axis}[width=\\columnwidth, height=5.4cm,',
         '      xlabel={undefended attack success rate (\\%)},',
         '      ylabel={change in ASR from the defense (pt)},',
         '      xmin=0, xmax=100, grid=major, grid style={gray!20},',
         '      tick label style={font=\\footnotesize},'
         ' label style={font=\\footnotesize}]',
         '      \\addplot[draw=black!45, dashed, forget plot] coordinates '
         '{(0,0) (100,0)};']
    pts, labs = [], []
    for m in present:
        if not (vasr.get(m) and dasr.get((m, 1))):
            continue
        u, dd = pct(vasr[m]), pct(dasr[(m, 1)])
        pts.append((u, dd - u))
        labs.append(DISP[m])
    b.append('      \\addplot[only marks, mark=*, mark size=2pt] coordinates {'
             + ' '.join(f'({x:.1f},{y:.1f})' for x, y in pts) + '};')
    for (x, y), l in zip(pts, labs):
        anchor = 'west' if x < 70 else 'east'
        dx = 2 if x < 70 else -2
        b.append(f'      \\node[font=\\scriptsize, anchor={anchor}] at '
                 f'(axis cs:{x + dx:.1f},{y:.1f}) {{{l}}};')
    b += ['    \\end{axis}', '  \\end{tikzpicture}',
          '  \\caption{Undefended attack success rate against the change the '
          'defense makes at $\\omega{=}1$. Points below the dashed line are models '
          'the defense helps, and the more vulnerable the base model, the larger '
          'the reduction.' + _worse_txt + '}',
          '  \\label{fig:benefit}', '\\end{figure}']
    write('fig_benefit.tex', '\n'.join(b) + '\n', f'{VAN} and {OMEGA}',
          'x: vanilla undefended_asr; y: defended_asr(omega=1) - undefended_asr')

# ---------------------------------------------------------------- fig_tradeoff
# DELIBERATELY NOT GENERATED. The utility/security asymmetry it showed is
# already carried by tab_vanilla plus one sentence of text, and the paper is
# against a hard page limit. Cut rather than kept for decoration.

# ---------------------------------------------------------------- tab_lown
if om:
    lo_t = hi_t = lo_n = hi_n = 0
    body = []
    for m in ORDER:
        g = [r for r in om if r['model'] == m and int(r['group_size']) == 1
             and r['k_prime'] == '1']
        if not g:
            continue
        lo = [int(r['attacker_kw_survived']) for r in g if int(r['n_retained']) <= 3]
        hi = [int(r['attacker_kw_survived']) for r in g if int(r['n_retained']) >= 4]
        lo_t += sum(lo); lo_n += len(lo); hi_t += sum(hi); hi_n += len(hi)
        body.append(f'    {DISP[m]} & {pct(lo):.0f}\\% ($N{{=}}{len(lo)}$) & '
                    f'{pct(hi):.0f}\\% ($N{{=}}{len(hi)}$) \\\\')
    b = [r'\begin{table}[t]', r'  \centering',
         r'  \caption{Attacker keyword survival at $\omega{=}1$, the setting the '
         r'released code implements and where Route~2 is inactive, split on '
         r'whether the query fell into the vacuous regime $n \le 3$.}',
         r'  \label{tab:lown}', r'  \begin{tabular}{lrr}', r'    \toprule',
         r'    model & $n \le 3$ & $n \ge 4$ \\', r'    \midrule'] + body + [
         r'    \midrule',
         f'    pooled & \\textbf{{{100*lo_t/lo_n:.0f}\\%}} ($N{{=}}{lo_n}$) & '
         f'\\textbf{{{100*hi_t/hi_n:.0f}\\%}} ($N{{=}}{hi_n}$) \\\\',
         r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
    write('tab_lown.tex', '\n'.join(b) + '\n', OMEGA,
          'group_size=1, k_prime=1, split on n_retained')

# ---------------------------------------------------------------- tab_coverage
# A CONFOUND THIS TABLE AVOIDS. Pooling RealtimeQA over all
# six models while Natural Questions and HotpotQA were Mistral-7B only (those
# two corpora were never run on the other five). Since n depends on the model's
# abstention behaviour, that compared a six-model average against two
# single-model measurements and made the corpus look like the only variable
# when it was not. That pooling yields 4% / 16% / 43%, which is not what this
# table reports.
#
# The table now holds the model fixed at Mistral-7B across all three corpora,
# so the corpus IS the only variable: 3.5% / 9.5% / 43%. The ordering and the
# headline contrast are unchanged and the ratio widens.
#
# The second column reports the six-model range on RealtimeQA, the one corpus
# where we have it. It is the control for this table: model-to-model variation
# there spans 9.5-20.0 points, well inside the 3.5-to-43 corpus spread, which
# is the evidence that holding the model fixed does not hide a larger effect.
COV_MODEL = 'mistral7b-bedrock'
DSETS = [('omega_open_nq_k10.csv', 'Natural Questions'),
         ('omega_realtimeqa_k10_all.csv', 'RealtimeQA'),
         ('omega_hotpotqa_k10.csv', 'HotpotQA (multi-hop)')]
cov = []
for fn, lab in DSETS:
    # ARM CONFOUND. Pooling k'=0 and k'=1 for
    # Natural Questions and RealtimeQA, while HotpotQA contributes ONLY k'=0
    # (it ships no attacker targets, so no attacked arm exists). The clean arm
    # systematically shows MORE low-n queries, because a poisoned passage adds
    # a non-abstaining response and raises n. Pooling therefore diluted the two
    # corpora that have both arms and compared them against a corpus measured
    # on the arm that inflates the statistic.
    # Published as 3.5 / 9.5 / 43.0; like-for-like on k'=0 it is 5.0 / 11.0 / 43.0.
    allr = [r for r in rows(os.path.join(R, fn))
            if int(r.get('group_size', 1) or 1) == 1
            and str(r.get('k_prime', '0')).strip() == '0']
    rr = [r for r in allr if r.get('model') == COV_MODEL]
    if not rr:
        raise SystemExit(
            'tab_coverage: %s has no %s rows at group_size=1. This table must '
            'hold the model fixed across corpora; refusing to emit a confounded '
            'comparison.' % (fn, COV_MODEL))
    ns = [int(r['n_retained']) for r in rr]
    # per-model spread, only where more than one model was run on this corpus
    permodel = {}
    for r in allr:
        permodel.setdefault(r.get('model'), []).append(int(r['n_retained']))
    if len(permodel) > 1:
        fr_each = sorted(100.0 * sum(1 for n in v if n <= 3) / len(v)
                         for v in permodel.values())
        spread = f'{fr_each[0]:.1f}--{fr_each[-1]:.1f}\\%'
    else:
        spread = '--'
    cov.append((lab, sum(ns) / len(ns),
                100.0 * sum(1 for n in ns if n <= 3) / len(ns), spread, len(ns)))
if cov:
    b = [r'\begin{table}[t]', r'  \centering',
         r'  \caption{How often the vacuous regime occurs, by corpus '
         r'($\omega{=}1$, $k{=}10$, $\alpha{=}0.3$, unattacked arm). The model is held fixed at '
         r'Mistral-7B so that the corpus is the only variable. The final column '
         r'gives the range across all six models on the one corpus where we ran '
         r'them: model-to-model variation is far smaller than the spread across '
         r'corpora.}',
         r'  \label{tab:coverage}', r'  \setlength{\tabcolsep}{4pt}',
         r'  \begin{tabular}{lrrrr}', r'    \toprule',
         r'    & \multicolumn{4}{c}{Mistral-7B} \\',
         r'    \cmidrule(l){2-5}',
         r'    dataset & $N$ & mean $n$ & $n \le 3$ & six-model range \\',
         r'    \midrule']
    # N IS PRINTED because the smallest cell is 5 queries out of 100, and a
    # reader comparing 5.0% against 43.0% is entitled to see the denominator.
    # An earlier draft of Section 3 described these corpora as 200 questions
    # each; every file holds 100 distinct q_idx, and the 200 was a row count
    # (two arms per query) mistaken for a question count. Emitting N here from
    # the data means that particular error cannot recur silently.
    for lab, mn, fr, spread, nn in cov:
        cell = f'{fr:.1f}\\%'
        if fr > 40:
            cell = f'\\textbf{{{cell}}}'
        b.append(f'    {lab} & {nn} & {mn:.2f} & {cell} & {spread} \\\\')
    b += [r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
    write('tab_coverage.tex', '\n'.join(b) + '\n', ', '.join(f for f, _ in DSETS),
          f'group_size=1, k_prime=0 (clean arm, the only arm all three corpora '
          f'share), model={COV_MODEL}, fraction of rows with '
          f'n_retained<=3; final column is the per-model range over all models '
          f'present in that file')

# ---------------------------------------------------------------- tab_generalize
GEN = [(os.path.join(R, 'omega_realtimeqa_k10_all.csv'), 'RealtimeQA, $k{=}10$',
        'mistral7b-bedrock'),
       (os.path.join(R, 'omega_open_nq_k10.csv'), 'Natural Questions, $k{=}10$', None),
       (os.path.join(R, 'omega_realtimeqa_k12.csv'), 'RealtimeQA, $k{=}12$', None)]
gcols, gdata = set(), []
for path, lab, mfilt in GEN:
    rr = [r for r in rows(path) if r['k_prime'] == '1']
    if mfilt:
        rr = [r for r in rr if r['model'] == mfilt]
    d = collections.defaultdict(list)
    for r in rr:
        d[int(r['group_size'])].append(int(r['attacker_kw_survived']))
    if d:
        gcols |= set(d); gdata.append((lab, d))
if len(gdata) >= 2:
    ws = sorted(gcols)
    b = [r'\begin{table*}[t]', r'  \centering',
         "  \\caption{Route~2 replicated. Mistral-7B, $k'{=}1$. The $k{=}12$ row is "
         r'a group-structure control: $12$ divides evenly by $1,2,3,4,6$, so no '
         r'group is short and the poisoned passage is never left alone in a '
         r'remainder group, which separates the threshold effect from the in-group '
         r'contest. Dashes are configurations not run.}',
         r'  \label{tab:generalize}',
         r'  \begin{tabular}{l' + 'r' * len(ws) + '}', r'    \toprule',
         r'    setting & ' + ' & '.join(f'$\\omega{{=}}{w}$' for w in ws) + r' \\',
         r'    \midrule']
    for lab, d in gdata:
        cells = []
        for w in ws:
            if w not in d:
                cells.append('--')
            else:
                v = f'{pct(d[w]):.0f}\\%'
                cells.append(f'\\textbf{{{v}}}' if w >= 4 else v)
        b.append(f'    {lab} & ' + ' & '.join(cells) + r' \\')
    b += [r'    \bottomrule', r'  \end{tabular}', r'\end{table*}']
    write('tab_generalize.tex', '\n'.join(b) + '\n', '; '.join(f for f, _, _ in GEN),
          'k_prime=1, mistral7b-bedrock where the file holds several models')

# ---------------------------------------------------------------- tab_composite
cm = rows(os.path.join(R, 'composite.csv'))
if cm:
    d = collections.defaultdict(list)
    for r in cm:
        ks, ki = str(r.get('k_suppress', '')).strip(), str(r.get('k_inject', '')).strip()
        if ks == '' or ki == '' or r['k_prime'] == '0':
            continue
        d[(int(ks), int(ki))].append(int(r['attacker_kw_survived']))
    if d:
        b = [r'\begin{table}[t]', r'  \centering',
             r'  \caption{Splitting the budget between suppression and injection. '
             r'At every fixed total, survival is maximised by spending nothing on '
             r'suppression: a passage diverted from injection costs more in keyword '
             r'count than it gains in threshold reduction.}',
             r'  \label{tab:composite}', r'  \begin{tabular}{rrrr}', r'    \toprule',
             "    $k'$ & suppress & inject & survival \\\\", r'    \midrule']
        for (ks, ki) in sorted(d, key=lambda t: (t[0] + t[1], t[0])):
            v = d[(ks, ki)]
            cell = f'{pct(v):.0f}\\%'
            if ks == 0:
                cell = f'\\textbf{{{cell}}}'
            b.append(f'    {ks + ki} & {ks} & {ki} & {cell} ($N{{=}}{len(v)}$) \\\\')
        b += [r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
        write('tab_composite.tex', '\n'.join(b) + '\n',
              os.path.join(R, 'composite.csv'),
              'k_prime>0, grouped by (k_suppress, k_inject)')

# ---------------------------------------------------------------- fig_alpha
au = rows(os.path.join(R, 'alpha_utility.csv'))
if au:
    acc = collections.defaultdict(list)
    for r in au:
        c = str(r.get('defended_correct', '')).strip()
        if r['k_prime'] == '0' and c != '':
            acc[float(r['alpha'])].append(int(c))
    if len(acc) >= 3:
        als = sorted(acc)
        pts = ' '.join(f'({a},{pct(acc[a]):.1f})' for a in als)
        safe = 1.0 / 10
        b = [r'\begin{figure}[t]', r'  \centering', r'  \begin{tikzpicture}',
             r'    \begin{axis}[width=\columnwidth, height=5cm,',
             r'      xlabel={relative threshold $\alpha$},',
             r'      ylabel={clean accuracy (\%)},',
             r'      ymin=0, ymax=80, grid=major, grid style={gray!20},',
             r'      tick label style={font=\footnotesize},'
             r' label style={font=\footnotesize}]',
             f'      \\addplot[draw=none, fill=gray!12, forget plot] coordinates '
             f'{{(0.05,0) ({safe:.2f},0) ({safe:.2f},80) (0.05,80)}} \\closedcycle;',
             r'      \node[font=\scriptsize, anchor=south west, align=left] at '
             r'(axis cs:0.055,4) {$\mu\le1$ always\\(vacuous)};',
             f'      \\addplot[mark=*, mark size=1.8pt, thick] coordinates {{{pts}}};',
             r'    \end{axis}', r'  \end{tikzpicture}',
             r'  \caption{Clean accuracy against $\alpha$ (Mistral-7B, $k{=}10$, '
             r'$\omega{=}1$). Utility peaks at the shipped default $\alpha{=}0.3$ '
             r'and falls on both sides, so tuning for accuracy keeps $\alpha$ at '
             r'$0.3$. At that value the group size the defense recommends, '
             r'$\omega{=}3$, gives $G{=}4$ and $\mu{=}1.2$, one abstention from '
             r'vacuity.}',
             r'  \label{fig:alpha}', r'\end{figure}']
        write('fig_alpha.tex', '\n'.join(b) + '\n',
              os.path.join(R, 'alpha_utility.csv'),
              'k_prime=0, defended_correct, grouped by alpha')

# ---------------------------------------------------------------- tab_alpha
# The paper states alpha=0.2 for short-answer QA (Sec V-A); the released code
# defaults to 0.3. Theorem 1 puts the vacuity boundary at ceil(k/omega) <= 1/alpha,
# so the step sits at omega>=4 under the code default and at omega>=2 under the
# paper's. Both ladders, same model, same queries, side by side.
A02 = rows(os.path.join(R, 'omega_realtimeqa_k10_a0.2.csv'))
if A02 and om:
    MOD = 'mistral7b-bedrock'
    def ladder(rr, alpha):
        sv, vc, cl = (collections.defaultdict(list) for _ in range(3))
        for r in rr:
            if r['model'] != MOD:
                continue
            w = int(r['group_size'])
            if r['k_prime'] == '1':
                sv[w].append(int(r['attacker_kw_survived']))
                vc[w].append(1 if float(r['mu']) <= 1.0 else 0)
            elif r['k_prime'] == '0':
                c = str(r.get('defended_correct', '')).strip()
                if c:
                    cl[w].append(int(c))
        return sv, vc, cl
    s2, v2, c2 = ladder(A02, 0.2)
    s3, v3, c3 = ladder(om, 0.3)
    ws = sorted(set(s2) | set(s3))
    def cell(d, w, bold=False):
        if w not in d or not d[w]:
            return '--'
        t = f'{pct(d[w]):.0f}\\%'
        return f'\\textbf{{{t}}}' if bold else t
    b = [r'\begin{table}[t]', r'  \centering',
         r'  \caption{The vacuity boundary moves with $\alpha$ exactly as '
         r'Theorem~\ref{thm:unconditional} requires. Mistral-7B, RealtimeQA, '
         r"$k{=}10$, $k'{=}1$, same queries throughout. RobustRAG's paper "
         r'specifies $\alpha{=}0.2$ for short-answer QA; its released code '
         r"defaults to $\alpha{=}0.3$. Under the former, the defense's own "
         r'recommended $\omega{=}3$ is vacuous on every query.}',
         r'  \label{tab:alpha}', r'  \setlength{\tabcolsep}{4pt}',
         r'  \begin{tabular}{lrrr@{\hskip 12pt}rrr}', r'    \toprule',
         r'    & \multicolumn{3}{c}{$\alpha=0.2$ (paper)} & '
         r'\multicolumn{3}{c}{$\alpha=0.3$ (code)} \\',
         r'    \cmidrule(r){2-4}\cmidrule(l){5-7}',
         r'    $\omega$ & $\mu_{\max}$ & vac. & surv. & $\mu_{\max}$ & vac. & surv. \\',
         r'    \midrule']
    for w in ws:
        G = math.ceil(10 / w)
        m2, m3 = min(0.2 * G, 3), min(0.3 * G, 3)
        mark = r'$^\star$' if w == 3 else ''
        b.append(f'    {w}{mark} & {m2:.2f} & {cell(v2,w)} & '
                 f'{cell(s2,w,w in (2,3,4))} & {m3:.2f} & {cell(v3,w)} & '
                 f'{cell(s3,w,w in (4,5))} \\\\')
    b += [r'    \bottomrule', r'  \end{tabular}',
          r'  \\[2pt] \footnotesize $^\star$ the group size RobustRAG recommends.',
          r'\end{table}']
    write('tab_alpha.tex', '\n'.join(b) + '\n',
          f"{os.path.join(R,'omega_realtimeqa_k10_a0.2.csv')} and {OMEGA}",
          "mistral7b-bedrock only; vac. = % of rows with mu<=1; surv. = k_prime=1")

# ---------------------------------------------------------------- fig_mustep
# The empirical form of Proposition 1. CONDITIONING MATTERS: pooling every row
# with a realised mu mixes in (a) threshold modes where the mitigation
# deliberately RAISED mu and (b) adversaries strong enough to clear any
# threshold. Both wash out the effect being shown. Restrict to k'=1 under the
# upstream rule, which is the only pool in which mu is the manipulated variable.
import glob as _glob

# A bare glob over results/ was WRONG here and silently inflated this figure's
# N by 1,583 rows. Three files must be excluded:
#   fix_mistral_backup.csv    -- a backup, not a result
#   fix_realtimeqa_k10.csv    -- every row also appears in fix_..._all.csv
#   omega_realtimeqa_k10.csv  -- every row also appears in omega_..._all.csv
# The last two are earlier partial runs that the _all supersets absorbed, so
# globbing everything counted those rows twice. The conclusion did not change
# (mu<=1: 54.8% -> 56.4%; mu>1: 3.5% -> 3.6%), but the printed N did, and a
# reviewer re-running this script on the released files would not have
# reproduced the number the paper printed.
_SUPERSEDED = {
    'fix_mistral_backup.csv',
    'fix_realtimeqa_k10.csv',
    'omega_realtimeqa_k10.csv',
}
# Any results file not classified either way is a surprise: fail rather than
# silently fold an unreviewed file into a published figure.
# Files that must NOT enter the mu-step pool even though they carry a mu column.
#   theirattacks_*  : RobustRAG's own PIA/Poison. Same filter, DIFFERENT attack.
#                     Pooling them with our injection would silently redefine
#                     what Figure 'mustep' measures.
#   certify_*       : certification arm; no attacker_kw_survived column at all.
_NOT_MU = {
    'theirattacks_realtimeqa_k10.csv',
    'certify_n.csv', 'certify_floor2.csv',
    # the certify block ALSO writes a per-query CSV per mode. Those are clean-arm
    # (k'=0) rows with no attacker_kw_survived signal, so they must not enter the
    # mu-step pool either. Missing these was a real bug: asset generation would
    # have SystemExit'd after the paid runs.
    'certify_realtimeqa_n.csv', 'certify_realtimeqa_floor2.csv',
}
# omega_open_nq_k10_full.csv (500 items) is a SUPERSET of omega_open_nq_k10.csv
# (first 200). Once the full file exists the 200-item file must be excluded or
# those 200 queries are counted twice.
# ...but only once the full file really IS a superset. run_final.sh exits 1 on a
# failed or contaminated run and can leave a PARTIAL file behind; superseding on
# mere existence would then drop 1,000 good rows and push \nobs DOWN, which is
# the one direction the frozen abstract cannot absorb. Require all five omegas
# and at least as many rows before believing it.
_full = os.path.join(R, 'omega_open_nq_k10_full.csv')
if os.path.exists(_full):
    _fr = rows(_full)
    _fw = {r['group_size'] for r in _fr}
    _old_n = len(rows(os.path.join(R, 'omega_open_nq_k10.csv'))) \
        if os.path.exists(os.path.join(R, 'omega_open_nq_k10.csv')) else 0
    if _fw >= {'1', '2', '3', '4', '5'} and len(_fr) >= _old_n:
        _SUPERSEDED = _SUPERSEDED | {'omega_open_nq_k10.csv'}
    else:
        raise SystemExit(
            'make_paper_assets.py: omega_open_nq_k10_full.csv looks PARTIAL '
            '(%d rows, omegas %s vs %d rows in the 200-item file). It would '
            'supersede a larger file and shrink the corpus. Finish or delete '
            'the run before regenerating assets.'
            % (len(_fr), sorted(_fw), _old_n))

_KNOWN = _SUPERSEDED | _NOT_MU | {
    'omega_realtimeqa_k10_all.csv', 'vanilla_realtimeqa_k10.csv', 'sweep.csv',
    'fix_realtimeqa_k10_all.csv', 'omega_open_nq_k10.csv',
    'omega_hotpotqa_k10.csv', 'omega_realtimeqa_k12.csv', 'composite.csv',
    'alpha_utility.csv', 'omega_realtimeqa_k10_a0.2.csv',
    'fix_open_nq_k10.csv', 'lown.csv', 'lown_opennq_pilot.csv',
    'omega_open_nq_k10_full.csv',
}
_present = {os.path.basename(p) for p in _glob.glob(os.path.join(R, '*.csv'))}
# certify_<mode>_<model>.csv and certify_realtimeqa_<mode>_<model>.csv are
# written one per model by run_final.sh, so the set is open-ended and has to be
# matched by prefix rather than enumerated. They carry no attacker_kw_survived
# signal and must never enter the mu-step pool.
_certify_files = {f for f in _present if f.startswith('certify_')}
_NOT_MU |= _certify_files
_KNOWN |= _certify_files

# ...AND THEY MUST NOT BE COUNTED IN \nobs. Two separate duplications, each
# verifiable against the files themselves:
#
#  (a) each certify run writes the SAME 100 queries twice, once under
#      CERTIFY_COLS (certify_<mode>_<model>.csv) and once under PER_QUERY_COLS
#      (certify_realtimeqa_<mode>_<model>.csv). The (model,q_idx) sets are
#      identical. Counting both doubles every certified query.
#  (b) every per-query row is a cell fix_realtimeqa_k10_all.csv ALREADY holds:
#      all 100 of 100 keys (model,q_idx,alpha,beta,omega,mode,k,k',attack)
#      match. That is by design -- the certify runs reuse the cached clean-arm
#      inference and only add the `certified` bit -- so they contribute a new
#      COLUMN on existing observations, not new observations.
#
# Folding them in silently moved \nobs from 24,400 to 24,800, which would have
# gone into the frozen abstract as a number no re-run of this script could
# reproduce. Same failure the _SUPERSEDED set exists to prevent; different
# cause, so it gets its own set rather than being smuggled into that one.
_DERIVED = set(_certify_files)
_unknown = _present - _KNOWN
if _unknown:
    raise SystemExit(
        'make_paper_assets.py: unclassified result file(s) %s.\n'
        'Add each to _KNOWN (a real input) or _SUPERSEDED (a backup or a '
        'partial run absorbed by an _all superset) before regenerating '
        'assets. Refusing to guess.' % sorted(_unknown))

_MU_FILES = sorted(_present - _SUPERSEDED - _NOT_MU)
mb = collections.defaultdict(list)
_nfiles = set()
for _f in [os.path.join(R, f) for f in _MU_FILES]:
    for r in rows(_f):
        if r.get('k_prime') != '1':
            continue
        if str(r.get('threshold_mode', 'n')).strip() not in ('', 'n'):
            continue
        if str(r.get('filter_only', '')).strip() in ('True', '1'):
            continue
        try:
            mu = float(r['mu']); sv = int(r['attacker_kw_survived'])
        except (ValueError, KeyError):
            continue
        # Right-closed bins (x-0.5, x], labelled by the upper edge, so that no bin
        # straddles the vacuity boundary. Rounding to the nearest 0.5 put the 869
        # rows at mu=1.2 (non-vacuous, ~2% survival) into the mu=1 bar and into
        # the "mu <= 1" pool, which halved the vacuous bar and understated the
        # split (56% vs the true 72%).
        mb[math.ceil(round(mu, 6) * 2) / 2].append(sv)
        _nfiles.add(os.path.basename(_f))
mb = {k: v for k, v in mb.items() if len(v) >= 100}      # drop edge bins
if len(mb) >= 4:
    ks = sorted(mb)
    coords = ' '.join(f'({k},{pct(mb[k]):.1f})' for k in ks)
    lo = [x for k in ks if k <= 1.0 for x in mb[k]]
    hi = [x for k in ks if k > 1.0 for x in mb[k]]
    _last_vac = max(k for k in ks if k <= 1.0)
    _first_non = min(k for k in ks if k > 1.0)
    b = [r'\begin{figure}[t]', r'  \centering', r'  \begin{tikzpicture}',
         r'    \begin{axis}[width=\columnwidth, height=5cm,',
         r'      xlabel={realised threshold $\mu$},',
         r'      ylabel={attacker survival (\%)},',
         r'      ybar, bar width=7pt, ymin=0, ymax=100, xmin=-0.4, xmax=3.4,',
         r'      xtick={0,0.5,1,1.5,2,2.5,3},',
         r'      grid=major, grid style={gray!20},',
         r'      tick label style={font=\footnotesize},'
         r' label style={font=\footnotesize}]',
         # In an ybar axis EVERY \addplot is rendered as bars, so the usual
         # shading-by-addplot trick silently produces four thin grey bars
         # instead of a region. Use \fill with axis cs coordinates instead.
         r'      \fill[gray!15] (axis cs:-0.4,0) rectangle (axis cs:1.25,100);',
         r'      \node[font=\scriptsize, anchor=north west, align=left] at '
         r'(axis cs:-0.33,97) {$\mu\le1$: filter\\admits everything};',
         r'      \addplot[fill=black!55, draw=black] coordinates {' + coords + '};',
         r'    \end{axis}', r'  \end{tikzpicture}',
         r'  \caption{Proposition~\ref{prop:vacuity} measured. Attacker survival '
         r'against the threshold the defense actually realised, pooled over every '
         f'model, corpus and $\\omega$ ($k\'{{=}}1$, upstream rule, $N={len(lo)+len(hi)}$). '
         r'Each bar covers $(x-0.5,\,x]$, so no bar straddles $\mu = 1$. '
         f'Survival is ${pct(lo):.0f}\\%$ where $\\mu \\le 1$ and ${pct(hi):.0f}\\%$ '
         f'above it, falling from ${pct(mb[_last_vac]):.0f}\\%$ in the last vacuous bar '
         f'to ${pct(mb[_first_non]):.0f}\\%$ in the next. Survival in the shaded region '
         r'stays below $100\%$ because a vacuous filter is necessary for the attack '
         r'but not sufficient (Section~\ref{sec:omega}).}',
         r'  \label{fig:mustep}', r'\end{figure}']
    write('fig_mustep.tex', '\n'.join(b) + '\n',
          f'{len(_nfiles)} files under {R}/',
          "k_prime=1, threshold_mode in (n,''), filter_only off, right-closed "
          'bins (x-0.5, x] with N>=100')

# ---------------------------------------------------------------- fig_ndist
DS2 = [('omega_open_nq_k10.csv', 'Natural Questions'),
       ('omega_realtimeqa_k10_all.csv', 'RealtimeQA'),
       ('omega_hotpotqa_k10.csv', 'HotpotQA')]
series = []
for fn, lab in DS2:
    # SAME ARM CONFOUND AS tab_coverage. HotpotQA has no
    # attacked arm, so pooling k'=0 and k'=1 for the other two corpora compared
    # unlike populations. Hold the arm fixed at k'=0, the one all three share,
    # and hold the model fixed for the same reason the table does.
    rr = [r for r in rows(os.path.join(R, fn))
          if int(r.get('group_size', 1) or 1) == 1
          and str(r.get('k_prime', '0')).strip() == '0'
          and r.get('model') == COV_MODEL]
    if not rr:
        continue
    h = collections.Counter(int(r['n_retained']) for r in rr)
    tot = sum(h.values())
    series.append((lab, ' '.join(f'({n},{100.0 * h[n] / tot:.2f})'
                                 for n in range(0, 11))))
if len(series) >= 2:
    MK = ['*', 'square*', 'triangle*']
    b = [r'\begin{figure}[t]', r'  \centering', r'  \begin{tikzpicture}',
         r'    \begin{axis}[width=\columnwidth, height=5cm,',
         r'      xlabel={non-abstaining groups $n$ (at $\omega{=}1$, $k{=}10$)},',
         r'      ylabel={queries (\%)},',
         r'      xtick={0,2,4,6,8,10}, ymin=0, ymax=32, xmin=-0.5, xmax=10.5,',
         # Legend ABOVE the axis. Inside the frame it sat on the Natural
         # Questions peak at n=9,10 and greyed out the very points the
         # sentence about that corpus refers to.
         r'      legend style={font=\tiny, at={(0.5,1.02)}, '
         r'anchor=south, legend columns=3, draw=none, column sep=3pt, '
         r'/tikz/every even column/.append style={column sep=3pt}},',
         r'      legend cell align=left, grid=major, grid style={gray!20},',
         r'      tick label style={font=\footnotesize},'
         r' label style={font=\footnotesize}]',
         r'      \addplot[draw=none, fill=gray!15, forget plot] coordinates '
         r'{(-0.5,0) (3.5,0) (3.5,32) (-0.5,32)} \closedcycle;',
         r'      \node[font=\scriptsize, anchor=north west, align=left] at '
         r'(axis cs:-0.4,30.5) {vacuous\\$n\le3$};']
    for i, (lab, coords) in enumerate(series):
        b.append(f'      \\addplot[mark={MK[i % 3]}, mark size=1.5pt, thick] '
                 f'coordinates {{{coords}}};')
        b.append(f'      \\addlegendentry{{{lab}}}')
    b += [r'    \end{axis}', r'  \end{tikzpicture}',
          r'  \caption{Distribution of the non-abstaining group count $n$ by '
          r'corpus. The shaded band is the regime in which the filter is vacuous '
          r'at the shipped $\alpha{=}0.3$. Natural Questions barely enters it; '
          r'multi-hop HotpotQA places a large mass inside it, because a single '
          r'isolated passage cannot answer a question that needs two.}',
          r'  \label{fig:ndist}', r'\end{figure}']
    write('fig_ndist.tex', '\n'.join(b) + '\n',
          ', '.join(f for f, _ in DS2), 'group_size=1, histogram of n_retained')

# ---------------------------------------------------------------- fig_fixbars
# DELIBERATELY NOT GENERATED. A bar chart here pools over models what
# tab_fix already reports per model, per omega, per threshold mode -- it adds
# no information, and it competed with that table for float space badly enough
# to overlap it. Redundant figures are worth cutting even when the data exists.

# ---------------------------------------------------------------- fig_asr
if present and vasr:
    MK2 = ['*', 'square*', 'triangle*', 'diamond*', 'pentagon*', 'o']
    b = [r'\begin{figure}[t]', r'  \centering', r'  \begin{tikzpicture}',
         r'    \begin{axis}[width=\columnwidth, height=5.4cm,',
         r'      xlabel={passage group size $\omega$ \quad '
         r'($0 =$ undefended reference)},',
         r'      ylabel={attack success rate (\%)},',
         r'      xtick={0,1,2,3,4,5}, xticklabels={undef.,1,2,3,4,5},',
         r'      ymin=0, ymax=100, xmin=-0.3, xmax=5.3,',
         r'      legend style={font=\scriptsize, at={(0.02,0.98)}, '
         r'anchor=north west, draw=none, fill opacity=0.85, text opacity=1},',
         r'      legend cell align=left, grid=major, grid style={gray!20},',
         r'      tick label style={font=\footnotesize},'
         r' label style={font=\footnotesize}]',
         r'      \addplot[draw=none, fill=gray!12, forget plot] coordinates '
         r'{(3.5,0) (5.3,0) (5.3,100) (3.5,100)} \closedcycle;']
    for i, m in enumerate(present):
        if not (vasr.get(m) and dasr.get((m, 1))):
            continue
        pts = [f'(0,{pct(vasr[m]):.1f})']
        pts += [f'({w},{pct(dasr[(m, w)]):.1f})' for w in OMEGAS
                if dasr.get((m, w))]
        b.append(f'      \\addplot[mark={MK2[i % len(MK2)]}, mark size=1.5pt, '
                 f'thick] coordinates {{{" ".join(pts)}}};')
        b.append(f'      \\addlegendentry{{{DISP[m]}}}')
    b += [r'    \end{axis}', r'  \end{tikzpicture}',
          r'  \caption{Attack success rate, with the undefended system as the '
          r'left-most point of every curve. Two things are visible that the '
          r'keyword-survival view cannot show: the defense starts far below its '
          r'own undefended baseline for five models but \emph{above} it, not '
          r'significantly, for Llama-3.3-70B, and even in the shaded vacuous region the curves do '
          r'not return to their undefended levels: the aggregation step '
          r'retains some effect after the filter has stopped working.}',
          r'  \label{fig:asr}', r'\end{figure}']
    write('fig_asr.tex', '\n'.join(b) + '\n', f'{VAN} and {OMEGA}',
          'x=0 is vanilla undefended_asr; x>=1 is defended_asr by group_size')

# ---------------------------------------------------------------- tab_certify
# Certified accuracy under RobustRAG's own threshold vs the floor, paired on
# (model, q_idx). This is what turns Proposition 3 from "the algorithm carries
# over" into a measured trade-off.
#
# THE TWO THRESHOLDS ARE DIFFERENT NUMBERS. The `mu` column is the INFERENCE
# threshold, min(alpha*n, beta). certify() in src/defense.py computes its own on
# n PLUS the corruption size and refuses when that falls to k' or below:
#     count_threshold = self._mu(non_abs_cnt + corruption_size)
#     if count_threshold <= corruption_size: return False
# So the degenerate branch fires on min(alpha*(n+k'), beta) <= k', NOT on
# mu <= k'. Using the mu column here gave 49 queries and implied 6 gained where
# the pairing found 5; using the threshold certify() actually evaluates gives 41
# and reconciles exactly. n is recovered from the per-query CSV of the same run.
_cert_n = sorted(_glob.glob(os.path.join(R, 'certify_n_*.csv')))
_cert_f = sorted(_glob.glob(os.path.join(R, 'certify_floor2_*.csv')))
if _cert_n and _cert_f:
    def _load_cert(paths):
        out = {}
        for _p in paths:
            for _r in rows(_p):
                out[(_r['model'], _r['q_idx'])] = _r
        return out

    _cn, _cf = _load_cert(_cert_n), _load_cert(_cert_f)
    _nret = {}
    for _p in _glob.glob(os.path.join(R, 'certify_realtimeqa_n_*.csv')):
        for _r in rows(_p):
            _nret[(_r['model'], _r['q_idx'])] = int(_r['n_retained'])

    _models = [m for m in ORDER
               if any(k[0] == m for k in _cn) and any(k[0] == m for k in _cf)]
    _b = _c = _deg = _deg_gain = 0
    _lines = []
    for _m in _models:
        _keys = sorted(set(k for k in _cn if k[0] == _m)
                       & set(k for k in _cf if k[0] == _m))
        if not _keys:
            continue
        _an = [int(_cn[k]['certified']) for k in _keys]
        _af = [int(_cf[k]['certified']) for k in _keys]
        _mb = sum(1 for x, y in zip(_an, _af) if x == 1 and y == 0)
        _mc = sum(1 for x, y in zip(_an, _af) if x == 0 and y == 1)
        _b += _mb
        _c += _mc
        # n_retained lives only in the per-query CSV. If that file is missing
        # for a model that IS in the pairing, skipping it silently would shrink
        # the degenerate-branch count the paper prints, with nothing to say so.
        # Refuse instead.
        _miss = [k for k in _keys if k not in _nret]
        if _miss:
            raise SystemExit(
                'tab_certify: %d queries for %s have a certify row but no '
                'per-query row, so n_retained cannot be recovered and the '
                'degenerate-branch count would be understated. Missing file is '
                'likely results/certify_realtimeqa_n_%s.csv. Re-run certify for '
                'that model.' % (len(_miss), _m, _m))
        for k in _keys:
            _r = _cn[k]
            _a, _bt, _kp = float(_r['alpha']), float(_r['beta']), int(_r['k_prime'])
            _n = _nret[k]
            if min(_a * (_n + _kp), _bt) <= _kp:
                _deg += 1
                if int(_cf[k]['certified']) == 1:
                    _deg_gain += 1
        _lines.append(f'    {DISP[_m]} & {len(_keys)} & '
                      f'{100.0 * sum(_an) / len(_an):.0f}\\% & '
                      f'{100.0 * sum(_af) / len(_af):.0f}\\% & '
                      f'{_mb} & {_mc} \\\\')

    def _exact_binom(b, c):
        n = b + c
        if n == 0:
            return 1.0
        return min(1.0, sum(math.comb(n, i)
                            for i in range(0, min(b, c) + 1)) / 2 ** n * 2)

    _p = _exact_binom(_b, _c)
    # Section VIII relates certdeggain to certc in words. At three models they
    # were equal (5 and 5) and the prose said "every query gained"; at six they
    # are 10 and 11 and that sentence became false. Sanity-check the relation
    # rather than trusting a sentence written against older data.
    if _deg_gain > _c:
        raise SystemExit(
            'tab_certify: %d queries gained via the degenerate branch but only '
            '%d gained overall. A query cannot be rescued by the branch without '
            'being a gain; the two counts disagree, so one of them is wrong.'
            % (_deg_gain, _c))
    # SECTION VIII SAYS "The floor costs nothing" AND "A zero on the losing
    # side". Those are words, not macros, so they do not follow the data. A
    # six-model run with b>0 would leave the paper asserting something its own
    # table contradicts. Fail here instead, because correcting it means rewriting
    # the prose, which no regeneration can do.
    if _b > 0:
        raise SystemExit(
            'tab_certify: b = %d, so the floor now costs %d quer%s its '
            'certificate. Section VIII (sections/08-fix.tex, subsection '
            '"What the floor costs in certified accuracy") states "The floor '
            'costs nothing" and "A zero on the losing side", and the caption '
            'here said the same. Rewrite that prose to report the trade '
            'honestly before regenerating. p = %.3f on %d discordant pairs.'
            % (_b, _b, 'y' if _b == 1 else 'ies', _p, _b + _c))
    if _lines:
        b = [r'\begin{table}[t]', r'  \centering',
             r"  \caption{Certified accuracy under RobustRAG's threshold "
             r'($\mu = \min(\alpha n, \beta)$) against the floored rule '
             r'($\tilde\mu = \max(2, \min(\alpha n, \beta))$), paired per query '
             r'at $k^{\prime}{=}1$. $b$ counts queries certified upstream but not under '
             r'the floor; $c$ the reverse.}'
             + (r' %% b=0: no query loses its certificate.' if _b == 0 else ''),
             r'  \label{tab:certify}', r'  \setlength{\tabcolsep}{4pt}',
             r'  \begin{tabular}{lrrrrr}', r'    \toprule',
             r'    model & $N$ & upstream & floored & $b$ & $c$ \\',
             r'    \midrule'] + _lines + [
             r'    \midrule',
             f'    pooled & {sum(1 for k in _cn if k in _cf)} & & & '
             f'\\textbf{{{_b}}} & \\textbf{{{_c}}} \\\\',
             r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
        write('tab_certify.tex', '\n'.join(b) + '\n',
              ', '.join(os.path.basename(x) for x in _cert_n + _cert_f),
              'paired on (model,q_idx); b/c are McNemar discordant counts')
        # How often certify()'s threshold differs from the inference path's.
        # They coincide only where BOTH saturate at beta, so this is not a bug
        # count -- it is the size of the gap this paper is about, measured.
        _same = _diff = 0
        for k in _cn:
            if k not in _cf:
                continue
            _r = _cn[k]
            _a, _bt, _kp = float(_r['alpha']), float(_r['beta']), int(_r['k_prime'])
            _n = _nret.get(k)
            if _n is None:
                continue
            if abs(min(_a * _n, _bt) - min(_a * (_n + _kp), _bt)) < 1e-9:
                _same += 1
            else:
                _diff += 1
        _facts = (f'\\newcommand{{\\certdiff}}{{{_diff}}}\n'
                  f'\\newcommand{{\\certsame}}{{{_same}}}\n'
                  f'\\newcommand{{\\certtotal}}{{{_same + _diff}}}\n'
                  f'\\newcommand{{\\certb}}{{{_b}}}\n'
                  f'\\newcommand{{\\certc}}{{{_c}}}\n'
                  f'\\newcommand{{\\certp}}{{{_p:.3f}}}\n'
                  f'\\newcommand{{\\certdeg}}{{{_deg}}}\n'
                  f'\\newcommand{{\\certdeggain}}{{{_deg_gain}}}\n'
                  f'\\newcommand{{\\certmodels}}{{{len(_models)}}}\n')
        write('certify_facts.tex', _facts, 'derived with tab_certify.tex',
              'every number Section VIII quotes about certification')
        print(f'  [certify] {len(_models)} models, b={_b} c={_c} p={_p:.3f}, '
              f'{_deg} degenerate, {_deg_gain} of those gained, '
              f'{_diff}/{_same + _diff} thresholds differ')

# ---------------------------------------------------------------- tab_theirs
# RobustRAG's OWN attacks (PIA, Poison) beside ours, same filter, same settings.
# This answers the obvious objection: that the vacuity finding is an artefact of
# the attack we wrote. It is a like-for-like comparison only because every run
# here uses the identical configuration (omega=1, mode n, alpha=0.3, beta=3,
# k=10, k'=1); the loader asserts that rather than trusting the filename.
_TH = os.path.join(R, 'theirattacks_realtimeqa_k10.csv')
_th = rows(_TH)
if _th:
    _bad = {(r['group_size'], r['threshold_mode'], r['alpha'], r['top_k'], r['k_prime'])
            for r in _th} - {('1', 'n', '0.3', '10', '1')}
    if _bad:
        raise SystemExit(
            'tab_theirs: %s contains runs at settings other than '
            "(omega=1, mode n, alpha=0.3, k=10, k'=1): %s. The comparison "
            'against our attack would not be like-for-like.' % (_TH, sorted(_bad)))

    # run_final.sh only merges the canonical file once all 12 parts are clean,
    # but a hand-assembled or truncated file would otherwise produce a table
    # missing rows with nothing to say so.
    _have = {(r['model'], r['attack']) for r in _th}
    _want = {(m, a) for m in ORDER for a in ('PIA', 'Poison')}
    if _have != _want:
        raise SystemExit(
            'tab_theirs: %s is incomplete. Missing %s. Finish the attacks run '
            'before generating assets; a partial table would understate the '
            'comparison without saying so.' % (_TH, sorted(_want - _have)))

    _ours = [r for r in om if r['group_size'] == '1' and r['k_prime'] == '1']
    _by = collections.defaultdict(list)
    for r in _th:
        _by[(r['model'], r['attack'])].append(r)
    for r in _ours:
        _by[(r['model'], 'KeywordInjection')].append(r)

    _atks = ['PIA', 'Poison', 'KeywordInjection']
    _lab = {'PIA': 'PIA', 'Poison': 'Poison', 'KeywordInjection': 'ours'}
    _rowsout, _lown = [], collections.defaultdict(list)
    for m in ORDER:
        if not any(_by.get((m, a)) for a in _atks):
            continue
        cells = []
        for a in _atks:
            v = _by.get((m, a), [])
            sv = [int(x['attacker_kw_survived']) for x in v
                  if str(x.get('attacker_kw_survived', '')).strip() != '']
            asr = [int(x['defended_asr']) for x in v
                   if str(x.get('defended_asr', '')).strip() != '']
            cells.append(f'{pct(sv):.0f}\\%' if sv else '--')
            cells.append(f'{pct(asr):.0f}\\%' if asr else '--')
            for x in v:
                if str(x.get('attacker_kw_survived', '')).strip() != '':
                    _lown[(a, int(x['n_retained']) <= 3)].append(
                        int(x['attacker_kw_survived']))
        _rowsout.append(f'    {DISP[m]} & ' + ' & '.join(cells) + ' \\\\')

    if _rowsout:
        b = [r'\begin{table}[t]', r'  \centering',
             r"  \caption{RobustRAG's own attacks beside ours, at identical "
             r'settings ($\omega{=}1$, $\alpha{=}0.3$, $\beta{=}3$, $k{=}10$, '
             r'$k^{\prime}{=}1$). For each attack: the rate at which the injected '
             r'keyword survives the filter, and the defended attack success '
             r'rate. The filter behaves the same way whichever attack supplies '
             r'the keyword, which is what the vacuity argument predicts.}',
             r'  \label{tab:theirs}', r'  \setlength{\tabcolsep}{3.5pt}',
             r'  \begin{tabular}{l' + 'rr' * len(_atks) + '}', r'    \toprule',
             r'    & ' + ' & '.join(r'\multicolumn{2}{c}{%s}' % _lab[a]
                                    for a in _atks) + r' \\',
             r'    model & ' + ' & '.join(['surv. & ASR'] * len(_atks)) + r' \\',
             r'    \midrule'] + _rowsout + [
             r'    \bottomrule', r'  \end{tabular}', r'\end{table}']
        write('tab_theirs.tex', '\n'.join(b) + '\n', f'{_TH} and {OMEGA}',
              "omega=1, k'=1; survival is attacker_kw_survived, ASR is defended_asr")

        # Explicit macro names. Deriving them by slicing the attack string gave
        # \theirspoisonlo from 'Poison' but \theirskeyworlo from
        # 'KeywordInjection', which does not match what the prose writes and
        # fails only at LaTeX time, in a section nobody rebuilds by hand.
        _MACRO = {'PIA': 'pia', 'Poison': 'poison', 'KeywordInjection': 'ours'}

        # IS OUR ATTACK JUST STRONGER? Pair each of their attacks against ours
        # on the same query and count discordant pairs. Per model this is 12
        # tests, so it needs the same Holm correction the rest of the paper
        # uses; none survives it. Pooled it is decisive, and the paper has to
        # say so rather than leave the reader to assume the instruments are
        # interchangeable.
        _pb = _pc = 0
        _permodel = []
        for _m in ORDER:
            for _a in ('PIA', 'Poison'):
                _A = {r['q_idx']: r for r in _by.get((_m, _a), [])}
                _B = {r['q_idx']: r for r in _by.get((_m, 'KeywordInjection'), [])}
                _ks = sorted(set(_A) & set(_B))
                if not _ks:
                    continue
                _x = sum(1 for k in _ks
                         if int(_A[k]['attacker_kw_survived']) == 1
                         and int(_B[k]['attacker_kw_survived']) == 0)
                _y = sum(1 for k in _ks
                         if int(_A[k]['attacker_kw_survived']) == 0
                         and int(_B[k]['attacker_kw_survived']) == 1)
                _pb += _x
                _pc += _y
                _permodel.append((f'{_m} {_a}', _x, _y))

        def _binom(x, y):
            _n = x + y
            if _n == 0:
                return 1.0
            return min(1.0, sum(math.comb(_n, i)
                                for i in range(0, min(x, y) + 1)) / 2 ** _n * 2)

        _ps = sorted(_binom(x, y) for _, x, y in _permodel)
        _M = len(_ps)
        _surv = sum(1 for i, _p2 in enumerate(_ps) if _p2 <= 0.05 / (_M - i)
                    and all(_ps[j] <= 0.05 / (_M - j) for j in range(i)))
        _pp = _binom(_pb, _pc)
        _theirswin = sum(1 for _, x, y in _permodel if x > y)
        print(f'  [theirs] pooled instrument test: b={_pb} c={_pc} p={_pp:.2e}; '
              f'{_surv} of {_M} per-model tests survive Holm; '
              f'theirs beat ours in {_theirswin} of {_M}')

        _facts = [f'\\newcommand{{\\theirspoolb}}{{{_pb}}}\n'
                  f'\\newcommand{{\\theirspoolc}}{{{_pc}}}\n'
                  f'\\newcommand{{\\theirspoolp}}{{{_pp:.1e}}}\n'
                  f'\\newcommand{{\\theirsntests}}{{{_M}}}\n'
                  f'\\newcommand{{\\theirsnholm}}{{{_surv}}}\n'
                  f'\\newcommand{{\\theirswin}}{{{_theirswin}}}\n']
        for a in _atks:
            _l, _h = _lown.get((a, True), []), _lown.get((a, False), [])
            if _l and _h:
                _nm = _MACRO[a]
                _facts.append(
                    f'\\newcommand{{\\theirs{_nm}lo}}{{{pct(_l):.0f}}}\n'
                    f'\\newcommand{{\\theirs{_nm}hi}}{{{pct(_h):.0f}}}\n'
                    f'\\newcommand{{\\theirs{_nm}nlo}}{{{len(_l)}}}\n')
                print(f'  [theirs] {a}: n<=3 survival {pct(_l):.0f}% (N={len(_l)}) '
                      f'vs {pct(_h):.0f}% (N={len(_h)})')
        if _facts:
            write('theirs_facts.tex', ''.join(_facts), _TH,
                  'low-n contrast repeated for each attack')

# Self-check on what we just wrote. \' in LaTeX is the acute-accent command:
# in math mode it is a hard error, in text mode it silently renders "RobustRAG's"
# as "RobustRAGs'". It gets here from \' inside a Python RAW string, where the
# backslash is not an escape and survives into the output. Caught only at build
# time otherwise, as two LaTeX errors and two malformed captions.
_acc = []
for _f in sorted(_glob.glob(os.path.join(OUT, '*.tex'))):
    _txt = open(_f).read()
    if "\\'" in _txt:
        _acc.append(os.path.basename(_f))
if _acc:
    raise SystemExit(
        "make_paper_assets.py: backslash-apostrophe reached the generated "
        "LaTeX in %s. That is the acute-accent command, not an apostrophe. "
        "Find the raw string in this file and use a plain ' (or k^{\\prime} "
        "for k-prime in math mode)." % ', '.join(_acc))

print('\ndone. \\input these from the section files; never edit generated/ by hand.')


# =====================================================================
# Derived corpus size. The paper quoted 29,350 query-level observations in
# four places; that number matched NO computation over the released files and
# was evidently typed rather than derived. It is now emitted from the data.
# Written to generated/nobs.tex and used via \nobs so the four sites cannot
# drift apart again.
# =====================================================================
#
# COUNT DISTINCT OBSERVATIONS, NOT ROWS. Summing row counts
# gave 24,400, but the sweeps overlap: fix_* and omega_* both measure mode n at
# omega in {1,4} on the same queries, and with --use_cache the second run reuses
# the first run's responses, so those rows are the SAME measurement written
# twice. 1,261 rows are exact re-measurements. The honest figure is 23,139.
#
# The rule below is deliberately conservative: two rows collapse only if they
# agree on the corpus and on EVERY column except `run` (the run id, which
# differs by construction). Any row that differs in any measured value is
# counted separately, so this can only ever under-report duplication.
def _corpus(fn):
    for _d in ('open_nq', 'hotpotqa', 'realtimeqa'):
        if _d in fn:
            return _d
    return fn          # files with no corpus token never merge across files


_obs_files = sorted((_KNOWN - _SUPERSEDED - _DERIVED) & _present)
_nobs = 0
_rawrows = 0
_breakdown = []
_seen_obs = set()
for _f in _obs_files:
    _p = os.path.join(R, _f)
    if not os.path.exists(_p):
        raise SystemExit('make_paper_assets.py: expected result file missing: %s' % _f)
    _new = 0
    for _r in rows(_p):
        _rawrows += 1
        _k = (_corpus(_f),) + tuple(sorted((_c, str(_v).strip())
                                           for _c, _v in _r.items() if _c != 'run'))
        if _k not in _seen_obs:
            _seen_obs.add(_k)
            _new += 1
    _nobs += _new
    _breakdown.append((_f, _new))

with open(os.path.join(OUT, 'nobs.tex'), 'w') as fh:
    fh.write('%% Generated by make_paper_assets.py -- do not edit.\n')
    fh.write('%% Query-level observations, summed over the released result files\n')
    fh.write('%% that this script reads. Backups and partial runs absorbed by an\n')
    fh.write('%% _all superset are excluded (see _SUPERSEDED), as are the\n')
    fh.write('%% certification files, whose rows are cells the fix file already\n')
    fh.write('%% holds (see _DERIVED).\n')
    fh.write('%% Counts are DISTINCT observations: a row that repeats an\n')
    fh.write('%% identical measurement already counted (the fix and omega\n')
    fh.write('%% sweeps overlap at omega in {1,4}, mode n) is counted once.\n')
    for _f, _n in _breakdown:
        fh.write('%%   %-34s %6d\n' % (_f, _n))
    fh.write('%%   %-34s %6d\n' % ('TOTAL distinct', _nobs))
    fh.write('%%   %-34s %6d\n' % ('raw rows on disk', _rawrows))
    fh.write('%%   %-34s %6d\n' % ('exact re-measurements', _rawrows - _nobs))
    fh.write('\\newcommand{\\nobs}{%s}\n' % f'{_nobs:,}'.replace(',', '{,}'))

# THE ABSTRACT NO LONGER QUOTES THIS NUMBER AT ALL. It is frozen at
# registration (Tue 22 Sep) under a CfP that allows "no substantial changes"
# afterwards, while _nobs keeps moving: the remaining runs add to it, and the
# row-vs-distinct correction above moved it by 1,261 on its own. A frozen count
# is a claim that cannot be repaired when the data changes under it, and the
# breadth it was standing in for is carried by the dimensions the abstract
# already lists (six models, three corpora, five group sizes, the alpha-beta
# surface). The body quotes \nobs exactly, and the body is editable until 29 Sep.
_abs = os.path.join(os.path.dirname(OUT), 'sections', '00-abstract.tex')
if os.path.exists(_abs):
    _txt = open(_abs).read()
    _body = '\n'.join(l for l in _txt.splitlines() if not l.lstrip().startswith('%'))
    if '\\nobs' in _body:
        raise SystemExit(
            'make_paper_assets.py: sections/00-abstract.tex uses \\nobs. The '
            'abstract is frozen at registration and this number still moves '
            '(it changed by 1,261 on 20 Sep alone). Quote the dimensions '
            'there instead and leave \\nobs to the body.')
    for _stale in ('24{,}400', '24,400', '24{,}800', '24,800', '24{,}000', '24,000'):
        if _stale in _body:
            raise SystemExit(
                'make_paper_assets.py: sections/00-abstract.tex still contains '
                '%r, a corpus size that is no longer correct (distinct count is '
                '%s). Remove it before registration.' % (_stale, f'{_nobs:,}'))

print(f'[nobs] {_nobs} distinct query-level observations '
      f'({_rawrows} rows on disk, {_rawrows - _nobs} exact re-measurements) '
      f'over {len(_obs_files)} files -> generated/nobs.tex')
